version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    hostname: backend
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    networks:
      - mynetwork
    ports:
      - "8080:80"  # Mappa la porta 80 del container alla porta 8080 della tua macchina

networks:
  mynetwork:
    driver: bridge
