version: "3"

services:
  # Web server 1
  webserver1:
    image: nginx:latest
    container_name: webserver1
    networks:
      webnet1:
        aliases:
          - webserver1
    volumes:
      - C:/Users/francesco/Desktop/ngix/webserver1/index.html:/usr/share/nginx/html/index.html

  # Web server 2
  webserver2:
    image: nginx:latest
    container_name: webserver2
    networks:
      webnet2:
        aliases:
          - webserver2
    volumes:
      - C:/Users/francesco/Desktop/ngix/webserver2/index.html:/usr/share/nginx/html/index.html

  # Reverse Proxy
  proxy:
    image: nginx:latest
    container_name: proxy
    networks:
      webnet1:
        aliases:
          - proxy
      webnet2:
        aliases:
          - proxy
    volumes:
      - /mnt/c/Users/francesco/Desktop/ngix/proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

# Definizione delle reti personalizzate
networks:
  webnet1:
    driver: bridge
  webnet2:
    driver: bridge
